### ISSUE TITLE
Migrate to SublimeLinter org

### ISSUE THREAD

**Issue by sirreal** [SublimeLinter/SublimeLinter-gotype#10]
I'd like to migrate this to https://github.com/SublimeLinter Org. I'm not using it and would like to look for another maintainer.

@groteworld can we do this?

**Comment by groteworld** [comment]
I'm totally ok with transferring to the SublimeLinter org, but I'd prefer if you handled the process of finding a new maintainer. That said, the fact that you are even trying to be responsible about making sure it's looked over makes you are 1000% better than the plethora of contrib-linters that go unmaintained (myself included). Either way, having it in the org would definitely be beneficial to making sure it could be maintained easily in the future.

You should be able to do the transfer yourself, but let me know if you need any help.

**Comment by sirreal** [comment]
See https://github.com/SublimeLinter/package_control_channel/pull/54
